[[news]]
date = "Aug 2026"
content = "Presented my work at STAI-X'26: Statistics and Trustworthy AI for Cross (X)-Domain Acceleration, Harvard University, Cambridge, MA."

[[news]]
date = "Apr 2026"
content = "Presented my work at IMSI Workshop on Reinforcement Learning from Offline Data and Human Feedback, David Rubenstein Forum, Chicago, IL."

[[news]]
date = "Mar 2026"
content = "Presented my work at Graduate Student Lightning Talk, University of California, Santa Barbara, CA."

# [[news]]
# date = "Sept 2024"
# content = "Started my PhD in Statistics and Applied Probability at University of California, Santa Barbara💪"

# [[news]]
# date = "Jun 2024"
# content = "Graduated with a B.S. in Applied Statistics from Jiangxi University of Finance and Economics🎓"

